# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sam Schuna
description: >- # this means to ignore newlines until "baseurl:"
  Hey there. I’m a designer/illustrator born and raised in the Twin Cities of
  Minnesota that likes to make cool stuff. If you’d like to contact me for work
  or even just to chat, I’d be more than happy to hear from you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.samschuna.com" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:
  projects:
    order:
      - toughluckplayingcards.html
      - mnufc.html
      - artcrank2015.html
      - wheaties.html
      - illustrations.html
      - threadless.html
      - madcircusgala.html
      - endtable.html
      - imatelier.html
      - monsters.html
      - logos.html
      - peacecorps.html
      - unclejohns.html
      - veggieportraits.html
      - sketches.html
      - friends.html
      - shirts.html
      - comics.html
      - digitalpaintings.html
      - conceptart.html
      - oddsends.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
